lex lex.l				#compiling lex file
yacc -d grammer.y -o grammer.cc		#compiling yacc file
cc -c lex.yy.c -o lex.yy.o		#compiling output files generated by lex and yacc
c++ lex.yy.o grammer.cc -o exe		#to use c++ stls and headers this execution is necessary

rm grammer.cc				#this 4 steps are for removing the 				
rm grammer.hh				#files that are generated while compilation
rm lex.yy.c				#After generating exe file they are no longer 
rm lex.yy.o				#needed.

rm *~					#needed for removing temporary files created by editors.
					#may cause error like "cannot remove ‘*~’: No such file or directory"
					#not a issue at all
